### ISSUE TITLE
/etc merge?

### ISSUE THREAD

**Issue by wegel** [GrabbenD/ostree-utility#1]
First of all, this is pretty awesome. Playing with it is fun ;)

I was wondering why the `--no-merge` [in ostree.sh](https://github.com/GrabbenD/ostree-demo/blob/c9a08207835f8ac9287b49c6a264bb0b6b168f75/ostree.sh#L113)? Without it (eg, enabling `/etc` merge), one could make changes to config files in `/etc` (for example, /etc/{passwd,group,sudoers} and /etc/NetworkManager/*), and have those changes available accross deployments.

Thanks for an awesome project!

**Comment by GrabbenD** [comment]
I'm glad you like it!

I've updated the README with my vision for this project which should answer your question :)

Your usecase is valid though, I added a option to make it possible (`upgrade --merge`)

**Comment by wegel** [comment]
Thank you, that answers it indeed, I'll use `--merge` on my deployments personally, as my goal is to have a reproducible os that can be deployed on any of my machines, but still have per-machine configuration. I could manage /etc separately I guess (using git or something like that), but considering that OSTree already manages /etc, it feels like the correct place for now.

I'll keep playing with this for for sure; I already have it deployed on a laptop that I use semi-regularly to play with it.

Thanks again!
